### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by R-Teer** [MacEnhance/MEMiniMe#1]
Not currently showing up in macforge, is there a link to download the .bundle file?

**Comment by zqso** [comment]
Me also would like to have it even it is only at a beta build.
Hope a .bundle file will be released or at MacForge Store soon.

**Comment by nsklaus** [comment]
i need this for yesterday! 
awesome seeing it happening, good job.
here's hoping macForge will be working on m1 machines soon.

**Comment by WaskoGM** [comment]
Thanks a lot for this. It will solve Big Sur's biggest UI problem. Can't wait for bundle. When we can expect it?

**Comment by w0lfschild** [comment]
This is now available in MacForge.

**Comment by ctf0** [comment]
cant install it on m1 mac, no plugin can be installed 😢 

PS:
had to restart the pc to activate the plugin
