### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by hyiltiz** [MacEnhance/MEMiniMe#4]
It is unclear if it is means:
1. others are allowed to repackage as long as the re-packager do not claim sole ownership;
2. others are allowed neither to re-package nor claim ownership.
3. others are allowed to re-package and/or re-distribute as long as they do not claim *sole* ownership.

Neither of the first two interpretations is similar to a BSD license. BSD is closest to the third interpretation. It seems you want to prevent re-distribution and/or derivative work that do not contribute changes back. If you want to prevent re-distribution, it is no longer a FOSS license; you can edit MPL (Mozilla's license) a bit and go through the trademark route. Alternatively, you could just make it GPL so others are obligated to contribute back.

An ambiguous license prevents potential contributes from contributing.

**Comment by w0lfschild** [comment]
https://github.com/MacEnhance/MEMiniMe/commit/5e7fae0532f33c0ef3c6741b014a5772afb392b4
