### ISSUE TITLE
Can "NSWindowToolbarStyleUnifiedCompact" be set manually?

### ISSUE THREAD

**Issue by hrvstr** [MacEnhance/MEMiniMe#6]
Hi, let's say I don't want to disable SIP, install MacEnhance and this plugin. Could I get the same functionality manually somehow?

I know about reading and writing defaults with `defaults` and tried to look around for a key that's called `NSWindowToolbarStyleUnifiedCompact` but couldn't find it .

Ideally I want to be able to just do:
`defaults write com.apple.Finder NSWindowToolbarStyleUnifiedCompact true`

Is this possible?

**Comment by w0lfschild** [comment]
@hrvstr 

No. Otherwise there would be no point in this plugin.

**Comment by hrvstr** [comment]
Okay, thanks for the feedback. Seems like I misunderstood how all of this works.
